name: Apache Flink ClickHouse Head Connector Tests CI (Java)

on:
  schedule:
    # Run against ClickHouse head at 3:55pm every day
    - cron: "55 15 * * *"

jobs:
  test-flink-17:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        clickhouse: [ "head" ]
        flink: [ "1.17.2", "1.18.1", "1.19.3", "1.20.2"]
    name: Apache Flink ${{ matrix.flink }} ClickHouse Connector tests with ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
          FLINK_VERSION: ${{ matrix.flink }}
        with:
          arguments: :flink-connector-clickhouse-1.17:test
  test-flink-2:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        clickhouse: [ "head" ]
    name: Apache Flink 2.0.0 ClickHouse Connector tests with ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
        with:
          arguments: :flink-connector-clickhouse-2.0.0:test